# Generated by Django 5.0.1 on 2024-01-02 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniqueface', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectedFace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.BinaryField()),
            ],
        ),
        migrations.DeleteModel(
            name='UniqueImage',
        ),
    ]
